### ISSUE TITLE
add it in pypi

### ISSUE THREAD

**Issue by FASTANDEXTREME** [hyugogirubato/pyImagine#2]
setuptools is Deprecatated, add it in PyPi so it can be used using pip

**Comment by ItsCEED** [comment]
@FASTANDEXTREME 
I did refactored version and added it to PyPi.
https://github.com/ItsCEED/ImaginePy-Midjourney-Free-Alternative

Soon, ill dig more of their apps to see if there is anything valuable to be used like this.

kudos @hyugogirubato !

**Comment by hyugogirubato** [comment]
@ItsCEED 
Thank you for the addition on PyPi!
