### ISSUE TITLE
An error occurred  Bad Request

### ISSUE THREAD

**Issue by raymerjacque** [hyugogirubato/pyImagine#5]
An error occurred while making the request: 400 Client Error: Bad Request 
the server is down ?

**Comment by raymerjacque** [comment]
someone needs to decompile their latest app and see how the urls and prompts have changed.

**Comment by hyugogirubato** [comment]
I will check in a few hours if there have been any changes

**Comment by raymerjacque** [comment]
Thank you :)

The mobile app was updated and works, so they must have changed the prompt request URL...

**Comment by Qewertyy** [comment]
> someone needs to decompile their latest app and see how the urls and prompts have changed.

i tried but idk much about Android

**Comment by raymerjacque** [comment]
here is the fix, can you please update your files : https://github.com/skzhengkai/vyro.ai-imagine/blob/main/vyroai/imagine.js

**Comment by Qewertyy** [comment]
https://inferenceengine.vyro.ai/sdprem
 This endpoint still works you just need to add `style-id` of model in headers

**Comment by hyugogirubato** [comment]
The upgrade with the fixes is now available in version 1.7.5
