### ISSUE TITLE
You need to fix your models and styles. like this.

### ISSUE THREAD

**Issue by raymerjacque** [hyugogirubato/pyImagine#6]
Currently your script only processes styles, no models. the Imagine.art project works on both models and styles.

its meant to process [selected model]+[user prompt]+[style]

but right now everyone is processing it only [user prompt]+[style]

i have corrected the issue in my python version https://github.com/raymerjacque/vyro-imagine-ai

i suggest you take a look and update your script. this new method greatly improves the quality of images generated and is more inline with the website and mobile app.

i have also made a video detailing what i changed and why. see the video below.

https://youtu.be/N2Hy8BauaBc

**Comment by hyugogirubato** [comment]
@raymerjacque 
Sorry for the wait but I just updated the script, on the repo, will be updated very soon on pip

**Comment by raymerjacque** [comment]
noi dont mean the broken styles. im talking about splitting the models and styles. see the video i linked.

**Comment by hyugogirubato** [comment]
I updated the api from the latest app update but haven't made the transition to the new endpoints yet because it requires a bearer token which is generated from google anti- abuse and a whole protobuf process has to be redone
