### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by abi98213** [hyugogirubato/pyImagine#7]
It saying bad gateway

**Comment by sobhansajjadi** [comment]
:|

**Comment by abi98213** [comment]
Why is it not working

**Comment by hyugogirubato** [comment]
Their old endpoint is now dead, I now have to see what I can do with the token generation. I've already started working on it but I'm a bit busy at the moment...

**Comment by hyugogirubato** [comment]
Fix maybe tomorrow

**Comment by sobhansajjadi** [comment]
;-(

**Comment by hyugogirubato** [comment]
Server side issue fixed.
