### ISSUE TITLE
API is not free i think...

### ISSUE THREAD

**Issue by Shayan-Mazahir** [hyugogirubato/pyImagine#9]
![image](https://github.com/hyugogirubato/pyimagine/assets/76951294/3e1ab0ed-561d-41a0-ab04-d915e99fc7e8)
![image](https://github.com/hyugogirubato/pyimagine/assets/76951294/1440284d-3dcd-4041-a7e1-637ecdd44dab)

i am not sure, if its related but just letting you know 😉

**Comment by ItsCEED** [comment]
You are ona  very bad trip, especially since its coming from ipy discord server ahhahahaha

**Comment by mixmediayt** [comment]
> You are ona very bad trip, especially since its coming from ipy discord server ahhahahaha

**Comment by Shayan-Mazahir** [comment]
> You are ona very bad trip, especially since its coming from ipy discord server ahhahahaha

welp.... i am searching for some other API's... let me know if u know some

**Comment by hyugogirubato** [comment]
@mixmediayt Update in about 30 minutes, I'm trying but seems to work. Needs to connect now but still works..

**Comment by ItsCEED** [comment]
@hyugogirubato yo, hit me up on discord.

**Comment by hyugogirubato** [comment]
Send a private message/a friend request because I don't know your username @ItsCEED

**Comment by ItsCEED** [comment]
> Send a private message/a friend request because I don't know your username @ItsCEED

.ceed or hop on the server (in my repo)

**Comment by sobhansajjadi** [comment]
@hyugogirubato What is your username?

**Comment by Shayan-Mazahir** [comment]
> @mixmediayt Update in about 30 minutes, I'm trying but seems to work. Needs to connect now but still works..

14 hours... updates any?

**Comment by sobhansajjadi** [comment]
> @mixmediayt Update in about 30 minutes, I'm trying but seems to work. Needs to connect now but still works..

where is the update

**Comment by raymerjacque** [comment]
either something went wrong and update is delayed, or after their discussion they decided not to release it ... lol :D

either way, nothing you can do but wait and hope... or go buy a subscription and support ImaginePy and then use a api that supports the paid version :D

**Comment by Shayan-Mazahir** [comment]
> either something went wrong and update is delayed, or after their discussion they decided not to release it ... lol :D
> 
> either way, nothing you can do but wait and hope... or go buy a subscription and support ImaginePy and then use a api that supports the paid version :D

before buying i want to see the API.... cause in most cases we can use the API without a Bearer KEy

**Comment by Qewertyy** [comment]
so dead project?

**Comment by tristandevs** [comment]
> either something went wrong and update is delayed, or after their discussion they decided not to release it ... lol :D
> 
> either way, nothing you can do but wait and hope... or go buy a subscription and support ImaginePy and then use a api that supports the paid version :D

where can we buy?

**Comment by raymerjacque** [comment]
They have a web app and a playstore app. 

https://play.google.com/store/apps/details?id=com.vyroai.aiart

**Comment by hyugogirubato** [comment]
Server side issue fixed.
